name: Secret scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install trufflehog
        run: |
          python -m pip install --upgrade pip
          pip install trufflehog

      - name: Run trufflehog (git-history + filesystem)
        run: |
          echo "Running trufflehog scan..."
          trufflehog git --json file://$(pwd) | tee trufflehog-output.json || true
          if [ -s trufflehog-output.json ]; then
            echo "TruffleHog detected potential secrets. See trufflehog-output.json";
            cat trufflehog-output.json;
            # Fail the job so PRs are blocked when potential secrets are found
            exit 1;
          else
            echo "No findings from trufflehog.";
          fi
